### ISSUE TITLE
işlem devam ediyor mu çakıldı mı ?

### ISSUE THREAD

**Issue by ozzytr** [suphiyasin/Youtube-User-Finder#1]
merhaba işlemleri yaptıktan sonra deneme amaçlı scan.txt içine alt alta 2 tane türkçe kelime yazdım
![image](https://user-images.githubusercontent.com/6943658/183674940-d5bea37b-9b85-47a2-b00a-aeedb425ce1b.png)
ardından kaydedim test.php 'yi çağırdım fakat böyle kaldı:

![image](https://user-images.githubusercontent.com/6943658/183675040-de39ff1e-8e2c-449c-8017-d0f868dc7839.png)

- burada sınırsız aramaya devam mı edecek? 
- durma durdurma yok mu?
- bu sayfa 5dk dır böyle sanırım işlem bitti veya bir yerlerde çakıldı, sayfayı yenilemem mi gerek?
- baktığımda üstte bulduğu birkaç maili de maillist.txt içine kaydetmemiş
- böylece bırakmam mı gerek ? ne zaman ilerler ?

**Comment by suphiyasin** [comment]
Yazdığınız kelimeleri tek seferde tarayıp sonuçlayan bir oto aracıdır.
sizin manuel olarak yazıp çıkarttığınız sonuçlar oto araçda çıkmayabilir daha değişik sonuçlar çıkıyor .
durma durdurma tuşu yoktur.
yani kısacası sayfa çalıştığı anda kelimeleri arar ve sonucu verir birdaha çalışması için yenilemeniz gerekir.
aynı şekilde burdan geç cevap vermemin nedeni sorununuzu telegramdan çözmüş olmamızdı
iyi günler dilerim
